### PR TITLE
add CORS headers

### PR DESCRIPTION
**Pull request by briehl**
Probably not strictly necessary, but shouldn't hurt either, and really helpful for local development.

### CODE REVIEW

**Comment by jayrbolton** [comment]
:+1: :ok:

**Comment by jayrbolton** [comment]
Do you also want to add these?
```
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: *
```

**Comment by briehl** [comment]
I thought about that, and we probably just need GET and OPTIONS, if that.
Not sure how the browser handles fetching CSS, etc., but those two are likely safe. I don't think we need POST?

Should I throw together a new PR?

**Comment by jayrbolton** [comment]
Didn't mean POST, was just copying and pasting from an rpc service. Edited that out.

**Pull request merged**
